var
    mapData = {},
    x = Game.grid.cols,
    y = Game.grid.rows
    ;

mapData.landscape = {};

/* TERRAIN */

mapData.landscape.terrain = [
    [CONST_LANDSCAPE_TILE_WATER, CONST_LANDSCAPE_TILE_WATER, CONST_LANDSCAPE_TILE_WATER, CONST_LANDSCAPE_TILE_WATER, CONST_LANDSCAPE_TILE_WATER, CONST_LANDSCAPE_TILE_WATER, CONST_LANDSCAPE_TILE_WATER, CONST_LANDSCAPE_TILE_WATER, CONST_LANDSCAPE_TILE_WATER, CONST_LANDSCAPE_TILE_WATER, CONST_LANDSCAPE_TILE_WATER, CONST_LANDSCAPE_TILE_WATER, CONST_LANDSCAPE_TILE_WATER, CONST_LANDSCAPE_TILE_WATER, CONST_LANDSCAPE_TILE_WATER, CONST_LANDSCAPE_TILE_WATER, CONST_LANDSCAPE_TILE_WATER, CONST_LANDSCAPE_TILE_WATER, CONST_LANDSCAPE_TILE_WATER, CONST_LANDSCAPE_TILE_WATER],
    [CONST_LANDSCAPE_TILE_WATER, CONST_LANDSCAPE_TILE_WATER_CORNER_SMALL_NW, CONST_LANDSCAPE_TILE_WATER_HORIZONTAL_COAST_DOWN, CONST_LANDSCAPE_TILE_WATER_HORIZONTAL_COAST_DOWN, CONST_LANDSCAPE_TILE_WATER_HORIZONTAL_COAST_DOWN, CONST_LANDSCAPE_TILE_WATER_HORIZONTAL_COAST_DOWN, CONST_LANDSCAPE_TILE_WATER_HORIZONTAL_COAST_DOWN, CONST_LANDSCAPE_TILE_WATER_HORIZONTAL_COAST_DOWN, CONST_LANDSCAPE_TILE_WATER_HORIZONTAL_COAST_DOWN, CONST_LANDSCAPE_TILE_WATER_HORIZONTAL_COAST_DOWN, CONST_LANDSCAPE_TILE_WATER_HORIZONTAL_COAST_DOWN, CONST_LANDSCAPE_TILE_WATER_HORIZONTAL_COAST_DOWN, CONST_LANDSCAPE_TILE_WATER_HORIZONTAL_COAST_DOWN, CONST_LANDSCAPE_TILE_WATER_HORIZONTAL_COAST_DOWN, CONST_LANDSCAPE_TILE_WATER_HORIZONTAL_COAST_DOWN, CONST_LANDSCAPE_TILE_WATER_HORIZONTAL_COAST_DOWN, CONST_LANDSCAPE_TILE_WATER_HORIZONTAL_COAST_DOWN, CONST_LANDSCAPE_TILE_WATER_HORIZONTAL_COAST_DOWN, CONST_LANDSCAPE_TILE_WATER_CORNER_SMALL_NE, CONST_LANDSCAPE_TILE_WATER],
    [CONST_LANDSCAPE_TILE_WATER, CONST_LANDSCAPE_TILE_WATER_VERTICAL_COAST_RIGHT, CONST_LANDSCAPE_TILE_GRASS_COAST_CORNER_NW, CONST_LANDSCAPE_TILE_GRASS_HORIZONTAL_COAST, CONST_LANDSCAPE_TILE_GRASS_HORIZONTAL_COAST, CONST_LANDSCAPE_TILE_GRASS_HORIZONTAL_COAST, CONST_LANDSCAPE_TILE_GRASS_HORIZONTAL_COAST, CONST_LANDSCAPE_TILE_GRASS_HORIZONTAL_COAST, CONST_LANDSCAPE_TILE_GRASS_HORIZONTAL_COAST, CONST_LANDSCAPE_TILE_GRASS_HORIZONTAL_COAST, CONST_LANDSCAPE_TILE_GRASS_HORIZONTAL_COAST, CONST_LANDSCAPE_TILE_GRASS_HORIZONTAL_COAST, CONST_LANDSCAPE_TILE_GRASS_HORIZONTAL_COAST, CONST_LANDSCAPE_TILE_GRASS_HORIZONTAL_COAST, CONST_LANDSCAPE_TILE_GRASS_HORIZONTAL_COAST, CONST_LANDSCAPE_TILE_GRASS_HORIZONTAL_COAST, CONST_LANDSCAPE_TILE_GRASS_HORIZONTAL_COAST, CONST_LANDSCAPE_TILE_GRASS_COAST_CORNER_NE, CONST_LANDSCAPE_TILE_WATER_VERTICAL_COAST, CONST_LANDSCAPE_TILE_WATER],
    [CONST_LANDSCAPE_TILE_WATER, CONST_LANDSCAPE_TILE_WATER_VERTICAL_COAST_RIGHT, CONST_LANDSCAPE_TILE_GRASS_VERTICAL_COAST, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS_VERTICAL_COAST_RIGHT, CONST_LANDSCAPE_TILE_WATER_VERTICAL_COAST, CONST_LANDSCAPE_TILE_WATER],
    [CONST_LANDSCAPE_TILE_WATER, CONST_LANDSCAPE_TILE_WATER_VERTICAL_COAST_RIGHT, CONST_LANDSCAPE_TILE_GRASS_VERTICAL_COAST, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS_VERTICAL_COAST_RIGHT, CONST_LANDSCAPE_TILE_WATER_VERTICAL_COAST, CONST_LANDSCAPE_TILE_WATER],
    [CONST_LANDSCAPE_TILE_WATER, CONST_LANDSCAPE_TILE_WATER_VERTICAL_COAST_RIGHT, CONST_LANDSCAPE_TILE_GRASS_VERTICAL_COAST, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS_VERTICAL_COAST_RIGHT, CONST_LANDSCAPE_TILE_WATER_VERTICAL_COAST, CONST_LANDSCAPE_TILE_WATER],
    [CONST_LANDSCAPE_TILE_WATER, CONST_LANDSCAPE_TILE_WATER_VERTICAL_COAST_RIGHT, CONST_LANDSCAPE_TILE_GRASS_VERTICAL_COAST, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS_VERTICAL_COAST_RIGHT, CONST_LANDSCAPE_TILE_WATER_VERTICAL_COAST, CONST_LANDSCAPE_TILE_WATER],
    [CONST_LANDSCAPE_TILE_WATER, CONST_LANDSCAPE_TILE_WATER_VERTICAL_COAST_RIGHT, CONST_LANDSCAPE_TILE_GRASS_VERTICAL_COAST, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS_VERTICAL_COAST_RIGHT, CONST_LANDSCAPE_TILE_WATER_VERTICAL_COAST, CONST_LANDSCAPE_TILE_WATER],
    [CONST_LANDSCAPE_TILE_WATER, CONST_LANDSCAPE_TILE_WATER_VERTICAL_COAST_RIGHT, CONST_LANDSCAPE_TILE_GRASS_VERTICAL_COAST, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS_VERTICAL_COAST_RIGHT, CONST_LANDSCAPE_TILE_WATER_VERTICAL_COAST, CONST_LANDSCAPE_TILE_WATER],
    [CONST_LANDSCAPE_TILE_WATER, CONST_LANDSCAPE_TILE_WATER_VERTICAL_COAST_RIGHT, CONST_LANDSCAPE_TILE_GRASS_VERTICAL_COAST, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS_VERTICAL_COAST_RIGHT, CONST_LANDSCAPE_TILE_WATER_VERTICAL_COAST, CONST_LANDSCAPE_TILE_WATER],
    [CONST_LANDSCAPE_TILE_WATER, CONST_LANDSCAPE_TILE_WATER_VERTICAL_COAST_RIGHT, CONST_LANDSCAPE_TILE_GRASS_VERTICAL_COAST, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS, CONST_LANDSCAPE_TILE_GRASS_VERTICAL_COAST_RIGHT, CONST_LANDSCAPE_TILE_WATER_VERTICAL_COAST, CONST_LANDSCAPE_TILE_WATER],
    [CONST_LANDSCAPE_TILE_WATER, CONST_LANDSCAPE_TILE_WATER_VERTICAL_COAST_RIGHT, CONST_LANDSCAPE_TILE_GRASS_COAST_CORNER_SW, CONST_LANDSCAPE_TILE_GRASS_HORIZONTAL_COAST_DOWN, CONST_LANDSCAPE_TILE_GRASS_HORIZONTAL_COAST_DOWN, CONST_LANDSCAPE_TILE_GRASS_HORIZONTAL_COAST_DOWN, CONST_LANDSCAPE_TILE_GRASS_HORIZONTAL_COAST_DOWN, CONST_LANDSCAPE_TILE_GRASS_HORIZONTAL_COAST_DOWN, CONST_LANDSCAPE_TILE_GRASS_HORIZONTAL_COAST_DOWN, CONST_LANDSCAPE_TILE_GRASS_HORIZONTAL_COAST_DOWN, CONST_LANDSCAPE_TILE_GRASS_HORIZONTAL_COAST_DOWN, CONST_LANDSCAPE_TILE_GRASS_HORIZONTAL_COAST_DOWN, CONST_LANDSCAPE_TILE_GRASS_HORIZONTAL_COAST_DOWN, CONST_LANDSCAPE_TILE_GRASS_HORIZONTAL_COAST_DOWN, CONST_LANDSCAPE_TILE_GRASS_HORIZONTAL_COAST_DOWN, CONST_LANDSCAPE_TILE_GRASS_HORIZONTAL_COAST_DOWN, CONST_LANDSCAPE_TILE_GRASS_HORIZONTAL_COAST_DOWN, CONST_LANDSCAPE_TILE_GRASS_COAST_CORNER_SE, CONST_LANDSCAPE_TILE_WATER_VERTICAL_COAST, CONST_LANDSCAPE_TILE_WATER],
    [CONST_LANDSCAPE_TILE_WATER, CONST_LANDSCAPE_TILE_WATER_CORNER_SMALL_SW, CONST_LANDSCAPE_TILE_WATER_HORIZONTAL_COAST, CONST_LANDSCAPE_TILE_WATER_HORIZONTAL_COAST, CONST_LANDSCAPE_TILE_WATER_HORIZONTAL_COAST, CONST_LANDSCAPE_TILE_WATER_HORIZONTAL_COAST, CONST_LANDSCAPE_TILE_WATER_HORIZONTAL_COAST, CONST_LANDSCAPE_TILE_WATER_HORIZONTAL_COAST, CONST_LANDSCAPE_TILE_WATER_HORIZONTAL_COAST, CONST_LANDSCAPE_TILE_WATER_HORIZONTAL_COAST, CONST_LANDSCAPE_TILE_WATER_HORIZONTAL_COAST, CONST_LANDSCAPE_TILE_WATER_HORIZONTAL_COAST, CONST_LANDSCAPE_TILE_WATER_HORIZONTAL_COAST, CONST_LANDSCAPE_TILE_WATER_HORIZONTAL_COAST, CONST_LANDSCAPE_TILE_WATER_HORIZONTAL_COAST, CONST_LANDSCAPE_TILE_WATER_HORIZONTAL_COAST, CONST_LANDSCAPE_TILE_WATER_HORIZONTAL_COAST, CONST_LANDSCAPE_TILE_WATER_HORIZONTAL_COAST, CONST_LANDSCAPE_TILE_WATER_CORNER_SMALL_SE, CONST_LANDSCAPE_TILE_WATER],
    [CONST_LANDSCAPE_TILE_WATER, CONST_LANDSCAPE_TILE_WATER, CONST_LANDSCAPE_TILE_WATER, CONST_LANDSCAPE_TILE_WATER, CONST_LANDSCAPE_TILE_WATER, CONST_LANDSCAPE_TILE_WATER, CONST_LANDSCAPE_TILE_WATER, CONST_LANDSCAPE_TILE_WATER, CONST_LANDSCAPE_TILE_WATER, CONST_LANDSCAPE_TILE_WATER, CONST_LANDSCAPE_TILE_WATER, CONST_LANDSCAPE_TILE_WATER, CONST_LANDSCAPE_TILE_WATER, CONST_LANDSCAPE_TILE_WATER, CONST_LANDSCAPE_TILE_WATER, CONST_LANDSCAPE_TILE_WATER, CONST_LANDSCAPE_TILE_WATER, CONST_LANDSCAPE_TILE_WATER, CONST_LANDSCAPE_TILE_WATER, CONST_LANDSCAPE_TILE_WATER]
];

/* ROADS */

mapData.landscape.roads = new Array(x);
for (var _x = 0; _x < x; _x++) {
    mapData.landscape.roads[_x] = new Array(y);
}

mapData.landscape.roads[4][5] = CONST_ROAD_TILE_VERTICAL_END | CONST_ROAD_TYPE_COBBLESTONE;
mapData.landscape.roads[4][6] = CONST_ROAD_TILE_VERTICAL | CONST_ROAD_TYPE_COBBLESTONE;
mapData.landscape.roads[4][7] = CONST_ROAD_TILE_VERTICAL | CONST_ROAD_TYPE_COBBLESTONE;
mapData.landscape.roads[4][8] = CONST_ROAD_TILE_VERTICAL | CONST_ROAD_TYPE_COBBLESTONE;
mapData.landscape.roads[4][9] = CONST_ROAD_TILE_DIAGONAL | CONST_ROAD_TYPE_COBBLESTONE | CONST_ROAD_FLIP_Y;
mapData.landscape.roads[5][9] = CONST_ROAD_TILE_DIAGONAL | CONST_ROAD_TYPE_COBBLESTONE | CONST_ROAD_FLIP_X;
mapData.landscape.roads[5][10] = CONST_ROAD_TILE_DIAGONAL | CONST_ROAD_TYPE_COBBLESTONE | CONST_ROAD_FLIP_Y;
mapData.landscape.roads[6][10] = CONST_ROAD_TILE_HORIZONTAL | CONST_ROAD_TYPE_COBBLESTONE;
mapData.landscape.roads[7][10] = CONST_ROAD_TILE_HORIZONTAL | CONST_ROAD_TYPE_COBBLESTONE;
mapData.landscape.roads[8][9] = CONST_ROAD_TILE_DIAGONAL | CONST_ROAD_TYPE_COBBLESTONE;
mapData.landscape.roads[8][10] = CONST_ROAD_TILE_DIAGONAL | CONST_ROAD_TYPE_COBBLESTONE | CONST_ROAD_FLIP_X | CONST_ROAD_FLIP_Y;
mapData.landscape.roads[9][8] = CONST_ROAD_TILE_DIAGONAL | CONST_ROAD_TYPE_COBBLESTONE;
mapData.landscape.roads[9][9] = CONST_ROAD_TILE_DIAGONAL | CONST_ROAD_TYPE_COBBLESTONE | CONST_ROAD_FLIP_X | CONST_ROAD_FLIP_Y;
mapData.landscape.roads[10][8] = CONST_ROAD_TILE_HORIZONTAL | CONST_ROAD_TYPE_COBBLESTONE;
mapData.landscape.roads[11][8] = CONST_ROAD_TILE_HORIZONTAL | CONST_ROAD_TYPE_COBBLESTONE;
mapData.landscape.roads[12][8] = CONST_ROAD_TILE_CORNER | CONST_ROAD_TYPE_COBBLESTONE | CONST_ROAD_FLIP_X | CONST_ROAD_FLIP_Y;

/* RIVERS */

mapData.landscape.rivers = new Array(x);
for (var _x = 0; _x < x; _x++) {
    mapData.landscape.rivers[_x] = new Array(y);
}

mapData.landscape.rivers[7][6]  = CONST_RIVER_TYPE_DIRTY | CONST_RIVER_TILE_CORNER;
mapData.landscape.rivers[7][7]  = CONST_RIVER_TYPE_DIRTY | CONST_RIVER_TILE_VERTICAL;
mapData.landscape.rivers[7][8]  = CONST_RIVER_TYPE_DIRTY | CONST_RIVER_TILE_VERTICAL;
mapData.landscape.rivers[7][9]  = CONST_RIVER_TYPE_DIRTY | CONST_RIVER_TILE_VERTICAL;
mapData.landscape.rivers[7][10] = CONST_RIVER_TYPE_DIRTY | CONST_RIVER_TILE_VERTICAL;
mapData.landscape.rivers[7][11] = CONST_RIVER_TYPE_DIRTY | CONST_RIVER_TILE_VERTICAL;

mapData.landscape.rivers[8][2] = CONST_RIVER_TYPE_DIRTY | CONST_RIVER_TILE_VERTICAL;
mapData.landscape.rivers[8][3] = CONST_RIVER_TYPE_DIRTY | CONST_RIVER_TILE_VERTICAL;
mapData.landscape.rivers[8][4] = CONST_RIVER_TYPE_DIRTY | CONST_RIVER_TILE_VERTICAL;
mapData.landscape.rivers[8][5] = CONST_RIVER_TYPE_DIRTY | CONST_RIVER_TILE_VERTICAL;
mapData.landscape.rivers[8][6] = CONST_RIVER_TYPE_DIRTY | CONST_RIVER_TILE_CORNER | CONST_RIVER_FLIP_X | CONST_RIVER_FLIP_Y;

/* OBJECTS */

mapData.landscape.objects = new Array(x);
for (var _x = 0; _x < x; _x++) {
    mapData.landscape.objects[_x] = new Array(y);
}

mapData.landscape.objects[15][7] = 'obj1';

/* TOWNS */

mapData.towns = new Array(x);
for (var _x = 0; _x < x; _x++) {
    mapData.towns[_x] = new Array(y);
}

mapData.towns[4][6] = CONST_TOWN_TYPE_RAMPART;
mapData.towns[12][7] = CONST_TOWN_TYPE_CASTLE | CONST_TOWN_BUILDINGS_FORT;

/* RESOURCES */

mapData.resources = new Array(x);
for (var _x = 0; _x < x; _x++) {
    mapData.resources[_x] = new Array(y);
}

mapData.resources[9][10] = CONST_RESOURCE_TYPE_CHEST;
mapData.resources[10][2] = CONST_RESOURCE_TYPE_SULPHUR;
mapData.resources[10][3] = CONST_RESOURCE_TYPE_MERCURY;
mapData.resources[10][4] = CONST_RESOURCE_TYPE_GEM;
mapData.resources[10][5] = CONST_RESOURCE_TYPE_CRYSTAL;
mapData.resources[10][10] = CONST_RESOURCE_TYPE_WOOD;
mapData.resources[10][11] = CONST_RESOURCE_TYPE_ORE;
mapData.resources[11][11] = CONST_RESOURCE_TYPE_GOLD;

/* CREATURES */

mapData.creatures = new Array(x);
for (var _x = 0; _x < x; _x++) {
    mapData.creatures[_x] = new Array(y);
}

mapData.creatures[6][8] = CONST_CREATURE_LEVEL_7 | CONST_CREATURE_TYPE_NEUTRAL | CONST_CREATURE_SPECIAL_AZURE_DRAGON;

/* HEROES */

mapData.heroes = new Array(x);
for (var _x = 0; _x < x; _x++) {
    mapData.heroes[_x] = new Array(y);
}

mapData.heroes[12][8] = CONST_HERO_VALESKA;
